# docker 버전
version: '3.9'

services: # 컨테이너로 실행될 서비스
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:42
    env_file: .env
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:42
    env_file: .env
    expose:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception_network
    restart: always

networks:
  inception_network:

volumes:
  DB:
    driver: local
    driver_opts:
      device: /home/hyehan/data/MariaDB
      o: bind
      type: none
  WordPress:
    driver: local
    driver_opts:
      device: /home/hyehan/data/WP
      o: bind
      type: none