services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
  
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hyehan/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hyehan/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge