version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception_network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hyehan/data/MariaDB
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hyehan/data/MariaDB
      o: bind

networks:
  inception_network:
    driver: bridge