# docker 버전
version: '3.9'

services: # 컨테이너로 실행될 서비스
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge

volumes:
  db_vol:
    driver: local
    driver_opts:
      device: /home/hyehan/Inception_data/db_vol
      o: bind
      type: none
  wp_vol:
    driver: local
    driver_opts:
      device: /home/hyehan/Inception_data/wp_vol
      o: bind
      type: none